### ISSUE TITLE
FEAT: Favicon and SEO images

### ISSUE THREAD

**Issue by DexterStorey** [tedspare/hexle#4]
We should generate a favicon (I'm thinking just a "#") and seo image but it would be sick if the BG could be dynamic using this new feature at vercel edge https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation

IDK if it would work with the fav... we should try, but it will definitely work with social preview

**Comment by tedspare** [comment]
![palpatine-dewit](https://user-images.githubusercontent.com/36117635/197352802-324dd58e-7adb-4db3-84c0-4c71854915af.gif)

But for real, dynamic favicon with `#` on colored bg sounds seck

**Comment by DexterStorey** [comment]
I Think this is now implemented in #1

**Comment by DexterStorey** [comment]
The effect will be more dramatic when we do #3 <img width="349" alt="Screenshot 2022-11-03 at 12 34 45 PM" src="https://user-images.githubusercontent.com/36115192/199779866-6c53c7f1-4732-42f1-85e1-f864eb4b3cbb.png">
<img width="496" alt="Screenshot 2022-11-03 at 12 33 43 PM" src="https://user-images.githubusercontent.com/36115192/199779873-85135319-0375-4d86-8575-17e092b7a61f.png">
